apiVersion: apps/v1
kind: Deployment
metadata:
  name: simonapp01
spec:
  selector:
    matchLabels:
      app: simonapp01
  template:
    metadata:
      labels:
        app: simonapp01
    spec:
      containers:
      - name: simonapp01
        image: sbacr02.azurecr.io/simonapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
